apiVersion: v1
kind: ServiceAccount
metadata:
  name: codeio-api
  namespace: codeio

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: codeio-api
  namespace: codeio

rules:
  # Deployments
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - delete

  # Pods
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

  # Services
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - delete

  # PersistentVolumeClaims
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - create
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: codeio-api
  namespace: codeio

subjects:
  - kind: ServiceAccount
    name: codeio-api
    namespace: codeio

roleRef:
  kind: Role
  name: codeio-api
  apiGroup: rbac.authorization.k8s.io
