apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-pvc-6a50b42a20ee549ae42a1c12
  namespace: codeio

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi

  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-6a50b42a20ee549ae42a1c12
  namespace: codeio
  labels:
    app: worker-6a50b42a20ee549ae42a1c12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-6a50b42a20ee549ae42a1c12
  template:
    metadata:
      labels:
        app: worker-6a50b42a20ee549ae42a1c12
    spec:
      volumes:
        - name: workspace-volume
          persistentVolumeClaim:
            claimName: workspace-pvc-6a50b42a20ee549ae42a1c12

      initContainers:
        - name: workspace-init
          image: amazon/aws-cli:latest

          command:
            - /bin/sh
            - -c

          args:
            - |
              set -e

              echo "Checking workspace..."

              if [ "$(ls -A /workspace 2>/dev/null)" ]; then
                echo "Workspace already exists. Skipping restore."
                exit 0
              fi

              echo "Workspace empty. Restoring project..."

              aws s3 sync \
                s3://${R2_BUCKET}/projects/${PROJECT_ID}/ \
                /workspace \
                --endpoint-url=${R2_ENDPOINT}

              echo "Workspace restored successfully."

          env:
            - name: PROJECT_ID
              value: "6a50b42a20ee549ae42a1c12"

            - name: R2_BUCKET
              value: "codeio"

            - name: R2_ENDPOINT
              value: "https://476a8af774f0c346bd2705591a38f078.r2.cloudflarestorage.com"

            - name: AWS_DEFAULT_REGION
              value: "auto"

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: r2-secret
                  key: accessKey

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: r2-secret
                  key: secretKey

          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace

      containers:
        - name: worker
          image: workspace-service:latest
          imagePullPolicy: IfNotPresent
          # imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
            - containerPort: 8080
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace
          resources:
            # FUTURE Plan: Use ephemeral-storage to add space limits here
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"

        - name: workspace-sync
          image: codeio-workspace-sync:latest
          imagePullPolicy: IfNotPresent
          # imagePullPolicy: IfNotPresent

          env:
            - name: PROJECT_ID
              value: "6a50b42a20ee549ae42a1c12"

            - name: R2_BUCKET
              value: "codeio"

            - name: R2_ENDPOINT
              value: "https://476a8af774f0c346bd2705591a38f078.r2.cloudflarestorage.com"

            - name: AWS_DEFAULT_REGION
              value: "auto"

            - name: SYNC_INTERVAL
              value: "60"

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: r2-secret
                  key: accessKey

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: r2-secret
                  key: secretKey

          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: worker-svc-6a50b42a20ee549ae42a1c12
  namespace: codeio
spec:
  selector:
    app: worker-6a50b42a20ee549ae42a1c12
  ports:
    - protocol: TCP
      name: ws
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: user
      port: 3000
      targetPort: 3000
  type: ClusterIP
