apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-pvc-{{PROJECT_ID}}
  namespace: NAMESPACE

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: WORKING_SIZE

  storageClassName: STORAGE_CLASS

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-{{PROJECT_ID}}
  namespace: NAMESPACE
  labels:
    app: worker-{{PROJECT_ID}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-{{PROJECT_ID}}
  template:
    metadata:
      labels:
        app: worker-{{PROJECT_ID}}
    spec:
      volumes:
        - name: workspace-volume
          persistentVolumeClaim:
            claimName: workspace-pvc-{{PROJECT_ID}}

      imagePullSecrets:
        - name: ghcr-secret

      initContainers:
        - name: workspace-init
          image: amazon/aws-cli:latest

          command:
            - /bin/sh
            - -c

          # Old Commands - if r2 had new files, and the pod didnt, then it was not updatig it
          # args:
          #   - |
          #     set -e

          #     echo "Checking workspace..."

          #     echo "ProjectId: PROJECT_ID"

          #     if [ "$(ls -A /workspace 2>/dev/null)" ]; then
          #       echo "Workspace already exists. Skipping restore."
          #       exit 0
          #     fi

          #     echo "Workspace empty. Restoring project..."

          #     aws s3 sync \
          #       s3://${R2_BUCKET}/projects/${PROJECT_ID}/ \
          #       /workspace \
          #       --endpoint-url=${R2_ENDPOINT}

          #     echo "Workspace restored successfully."

          # This will always sync pod with r2, and delete files that dont exist in r2 but in pod
          # Potential Issue: There is an edge case where if the r2 is not synced yet and pod has the updated files
          # the pull will remove the non-synced files
          args:
            - |
              set -e

              echo "Syncing workspace..."

              echo "Restoring project..."

              aws s3 sync \
                s3://${R2_BUCKET}/projects/${PROJECT_ID}/ \
                /workspace \
                --endpoint-url=${R2_ENDPOINT} \
                --delete

              echo "Workspace restored successfully."

          env:
            - name: PROJECT_ID
              value: "{{PROJECT_ID}}"

            - name: R2_BUCKET
              value: "{{R2_BUCKET}}"

            - name: R2_ENDPOINT
              value: "{{R2_ENDPOINT}}"

            - name: AWS_DEFAULT_REGION
              value: "auto"

            - name: AWS_ACCESS_KEY_ID
              value: "{{R2_ACCESS_KEY}}"

            - name: AWS_SECRET_ACCESS_KEY
              value: "{{R2_SECRET_KEY}}"

          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace

      containers:
        - name: worker
          image: WORKER_IMAGE
          imagePullPolicy: IMAGE_PULL_POLICY
          # imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
            - containerPort: 8080
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace
          resources:
            # FUTURE Plan: Use ephemeral-storage to add space limits here
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

        - name: workspace-sync
          image: WORKSPACE_SYNC_IMAGE
          imagePullPolicy: IMAGE_PULL_POLICY
          # imagePullPolicy: IfNotPresent

          env:
            - name: PROJECT_ID
              value: "{{PROJECT_ID}}"

            - name: R2_BUCKET
              value: "{{R2_BUCKET}}"

            - name: R2_ENDPOINT
              value: "{{R2_ENDPOINT}}"

            - name: AWS_DEFAULT_REGION
              value: "auto"

            - name: SYNC_INTERVAL
              value: "{{SYNC_INTERVAL}}"

            - name: AWS_ACCESS_KEY_ID
              value: "{{R2_ACCESS_KEY}}"
              # valueFrom:
              #   secretKeyRef:
              #     name: r2-secret
              #     key: accessKey

            - name: AWS_SECRET_ACCESS_KEY
              value: "{{R2_SECRET_KEY}}"
              # valueFrom:
              #   secretKeyRef:
              #     name: r2-secret
              #     key: secretKey

          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: worker-svc-{{PROJECT_ID}}
  namespace: NAMESPACE
spec:
  selector:
    app: worker-{{PROJECT_ID}}
  ports:
    - protocol: TCP
      name: ws
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: user
      port: 3000
      targetPort: 3000
  type: ClusterIP
