apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeio-api
  labels:
    app: codeio-api
  namespace: codeio

spec:
  replicas: 1

  selector:
    matchLabels:
      app: codeio-api

  template:
    metadata:
      labels:
        app: codeio-api

    spec:
      serviceAccountName: codeio-api

      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: codeio-api
          image: ghcr.io/aman-gupta-404/codeio-api:v1.0.0
          # imagePullPolicy: IfNotPresent
          imagePullPolicy: Always

          ports:
            - containerPort: 3001
              protocol: TCP

          envFrom:
            - configMapRef:
                name: codeio-api-config
            - secretRef:
                name: codeio-api-secrets

          readinessProbe:
            httpGet:
              path: /api/health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: codeio-api
  namespace: codeio

spec:
  selector:
    app: codeio-api

  ports:
    - name: http
      port: 3001
      targetPort: 3001

  type: ClusterIP
